// src/components/menu/content/group.vue
<script setup lang="ts">
import type { MenuContentItemsGroupProps } from "@/types";
import { SidebarMenu } from "@/components/shadcn";
import ThemeSelector from "../theme/selector.vue";
import MenuItems from "./items.vue";

const props = defineProps<MenuContentItemsGroupProps>();
</script>

<template>
    <SidebarMenu v-if="props.group" class="h-full">
        <div v-for="(item, index) in props.group" :key="`mItem-${index}-${item.label || index}`" class="flex flex-col gap-2 h-full">
            <ThemeSelector :toggle-theme-menu="props.toggleThemeMenu" :theme-menu-open="props.themeMenuOpen" :index="index" :item="item" />
            <MenuItems :toggle-theme-menu="props.toggleThemeMenu" :index="index" :item="item" />
        </div>
    </SidebarMenu>
</template>

// src/components/menu/content/group.tsx
import type { MenuContentItemsGroupProps, MenuItem } from "@/types";
import { SidebarMenu } from "@/components";
import { ThemeSelector } from "../theme";
import { type JSX } from "react";
import MenuItems from "./items";

function MenuContentItemsGroup(props: MenuContentItemsGroupProps): JSX.Element | null {
    if (!props.group) return null;

    return (
        <SidebarMenu className="h-full">
            {props.group.map((item: MenuItem, index: number) => (
                <div key={`mItem-${index}-${item.label || index}`} className="flex flex-col gap-2 h-full">
                    <ThemeSelector toggleThemeMenu={props.toggleThemeMenu} themeMenuOpen={props.themeMenuOpen} index={index} item={item} />
                    <MenuItems toggleThemeMenu={props.toggleThemeMenu} index={index} item={item} />
                </div>
            ))}
        </SidebarMenu>
    );
}

export default MenuContentItemsGroup;
