// src/components/menu/content/index.vue
<script setup lang="ts">
import { SidebarContent, SidebarGroup, SidebarGroupContent } from "@/components/shadcn";
import type { MenuContentProps } from "@/types";
import MenuContentItemsGroup from "./group.vue";

const props = defineProps<MenuContentProps>();
</script>

<template>
    <SidebarContent v-if="props.groups" class="py-2 h-auto flex-none pr-11">
        <SidebarGroup
            class="border-b border-b-slate-200 dark:border-b-slate-600 last:border-none w-full"
            v-for="(group, index) in props.groups"
            :key="`group-${index}`"
        >
            <SidebarGroupContent class="gap-0">
                <MenuContentItemsGroup :group="group" :theme-menu-open="props.themeMenuOpen" :toggle-theme-menu="props.toggleThemeMenu" />
            </SidebarGroupContent>
        </SidebarGroup>
    </SidebarContent>
</template>

// src/components/menu/content/index.tsx
import { SidebarContent, SidebarGroup, SidebarGroupContent } from "@/components";
import type { MenuContentProps, MenuItemGroup } from "@/types";
import MenuContentItemsGroup from "./group";
import { type JSX } from "react";

export function MenuContent(props: MenuContentProps): JSX.Element | null {
    if (!props.groups) return null;

    return (
        <SidebarContent className="py-2 h-auto flex-none">
            {props.groups.map((group: MenuItemGroup, index: number) => (
                <SidebarGroup
                    key={`group-${index}`}
                    className="border-b border-b-slate-200 dark:border-b-slate-600 last:border-none w-full"
                >
                    <SidebarGroupContent className="gap-0">
                        <MenuContentItemsGroup group={group} themeMenuOpen={props.themeMenuOpen} toggleThemeMenu={props.toggleThemeMenu} />
                    </SidebarGroupContent>
                </SidebarGroup>
            ))}
        </SidebarContent>
    );
}
