// src/components/menu/index.tsx
import { Sidebar, SidebarInset, SidebarProvider, Popover, PopoverContent } from "@/components";
import { NavigationbarMenuProps } from "@/types";
import { MenuContent } from "./content";
import { MenuTrigger } from "./Trigger";
import { memo, useMemo } from "react";

const NavigationbarMenu = memo(function NavigationbarMenu(props: NavigationbarMenuProps) {
    const { groups, navbarMenuOpen, themeMenuOpen, toggleAccountMenu, toggleNavbarMenu, toggleThemeMenu, user } = props;

    const themeButtons = useMemo(() => [{ id: "system" }, { id: "light" }, { id: "dark" }], []);
    const showBaseMenuContent = !themeMenuOpen;

    const menuContent = useMemo(() => {
        return showBaseMenuContent
            ? groups
            : themeMenuOpen
              ? [[{ label: "Theme Settings", themes: themeButtons }]]
              : [[{ label: "Account Switcher" }]];
    }, [showBaseMenuContent, groups, themeMenuOpen, themeButtons]);

    return (
        <Popover open={navbarMenuOpen} onOpenChange={toggleNavbarMenu}>
            <MenuTrigger profile={user} />

            <PopoverContent className="w-56 overflow-hidden rounded-lg shadow-lg max-h-[calc(100vh-40rem)]" align="end">
                <SidebarProvider>
                    <SidebarInset className="bg-transparent h-auto">
                        <Sidebar collapsible="none">
                            <MenuContent
                                toggleAccountMenu={toggleAccountMenu}
                                toggleThemeMenu={toggleThemeMenu}
                                themeMenuOpen={themeMenuOpen}
                                groups={menuContent}
                                user={user}
                            />
                        </Sidebar>
                    </SidebarInset>
                </SidebarProvider>
            </PopoverContent>
        </Popover>
    );
});

export default NavigationbarMenu;

// src/components/menu/index.vue
<script setup lang="ts">
import { Popover, PopoverContent, SidebarProvider, SidebarInset, Sidebar } from "../shadcn";
import type { NavigationbarMenuProps } from "@/types";
import MenuTrigger from "./trigger.vue";
import { MenuContent } from "./content";
import { computed, ref, watch } from "vue";

const props = defineProps<NavigationbarMenuProps>();
const localOpen = ref(props.navbarMenuOpen);

watch(
    () => props.navbarMenuOpen,
    (newValue) => {
        localOpen.value = newValue;
    }
);

const themeButtons = [{ id: "system" }, { id: "light" }, { id: "dark" }];
const showBaseMenuContent = computed(() => !props.themeMenuOpen);

const content = computed(() => {
    return showBaseMenuContent.value
        ? props.groups
        : props.themeMenuOpen
          ? [[{ label: "Theme Settings", themes: themeButtons }]]
          : [[{ label: "Account Switcher" }]];
});
</script>

<template>
    <Popover v-model:open="localOpen" @update:open="props.toggleNavbarMenu">
        <MenuTrigger :profile="props.profile" />

        <PopoverContent class="w-56 overflow-hidden rounded-lg shadow-lg max-h-[calc(100vh-40rem)] mt-2" align="end">
            <SidebarProvider>
                <SidebarInset class="bg-transparent h-auto w-full">
                    <Sidebar collapsible="none" class="w-full">
                        <MenuContent
                            :toggle-account-menu="props.toggleAccountMenu"
                            :toggle-theme-menu="props.toggleThemeMenu"
                            :theme-menu-open="props.themeMenuOpen"
                            :groups="content"
                        />
                    </Sidebar>
                </SidebarInset>
            </SidebarProvider>
        </PopoverContent>
    </Popover>
</template>
