// src/components/profile/image.vue
<script setup lang="ts">
import type { ProfileImageProps } from "@/types";
import { cn } from "@/lib";

const props = defineProps<ProfileImageProps>();
</script>

<template>
    <img
        :class="cn('object-cover', props.class)"
        :alt="props.alt || 'Profile Picture'"
        :height="props.dimensions[0]"
        :width="props.dimensions[1]"
        :src="props.src || ''"
    />
</template>

// src/components/profile/image.tsx
import type { ProfileImageProps } from "@/types";
import { type JSX } from "react";
import { cn } from "@/lib";

const ProfileImage = (props: ProfileImageProps): JSX.Element => (
    <img
        className={cn("object-cover", props.className)}
        alt={props.alt || "Profile Picture"}
        height={props.dimensions[0]}
        width={props.dimensions[1]}
        src={props.src || ""}
    />
);

export default ProfileImage;
