// src/components/shadcn/ui/button/back.tsx
import { SidebarMenuButton } from "../sidebar";
import { MoveLeft } from "lucide-react";
import type { JSX } from "react";
import { cn } from "@/lib";

const BackButton = ({ btnText, onClick }: { onClick: () => void; btnText: string }): JSX.Element => (
    <SidebarMenuButton
        onClick={onClick}
        className={cn(
            "w-full rounded-md px-4 text-left text-sm text-slate-700 dark:text-slate-200",
            "hover:bg-slate-100 dark:hover:bg-slate-600 hover:cursor-pointer"
        )}
    >
        <div className="flex items-center gap-2 pl-1">
            <MoveLeft className="h-4 w-4" />
            <span className="font-medium">{btnText}</span>
        </div>
    </SidebarMenuButton>
);

export { BackButton };

// src/components/shadcn/ui/button/back.vue
<script setup lang="ts">
import { SidebarMenuButton } from "../sidebar";
import type { BackButtonProps } from "@/types";
import { MoveLeft } from "lucide-vue-next";

const props = defineProps<BackButtonProps>();
</script>

<template>
    <SidebarMenuButton class="w-full h-full rounded-md px-4 text-left text-slate-700" @click="props.onClick">
        <div class="flex items-center gap-2 hover:cursor-pointer w-full h-[30px] p-0">
            <MoveLeft class="h-5 w-5" />
            <span class="font-medium text-sm text-slate-700">{{ props.btnText }}</span>
        </div>
    </SidebarMenuButton>
</template>
