// src/components/shadcn/ui/button/default.vue
<script setup lang="ts">
import { buttonVariants } from "../../variants";
import type { ButtonProps } from "@/types";
import { cn } from "@/lib";

withDefaults(defineProps<ButtonProps>(), {
    variant: "default",
    size: "default",
    as: "button",
});

defineOptions({ inheritAttrs: false });
</script>

<template>
    <component :is="as" :class="cn(buttonVariants({ variant, size }), $attrs.class ?? '')" v-bind="$attrs">
        <slot />
    </component>
</template>

// src/components/shadcn/ui/button/default.tsx
import { buttonVariants } from "../../variants";
import { forwardRef, type JSX } from "react";
import { Slot } from "@radix-ui/react-slot";
import type { ButtonProps } from "@/types";
import { cn } from "@/lib";

const Button = forwardRef<HTMLButtonElement, ButtonProps>(({ className, variant, size, asChild = false, ...props }, ref): JSX.Element => {
    const Comp = asChild ? Slot : "button";
    return <Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />;
});

Button.displayName = "Button";

export { Button };
