// src/components/shadcn/ui/Button.vue
<script setup lang="ts">
import { buttonVariants } from "../variants";
import type { ButtonProps } from "@/types";
import { cn } from "flixburst-tailwind";
import { Primitive } from "reka-ui";

const props = withDefaults(defineProps<ButtonProps>(), {
    as: "button",
});
</script>

<template>
    <Primitive data-slot="button" :as="as" :as-child="asChild" :class="cn(buttonVariants({ variant, size }), props.class)">
        <slot />
    </Primitive>
</template>

// src/components/shadcn/ui/button.tsx
import { buttonVariants } from "../variants";
import { Slot } from "@radix-ui/react-slot";
import { ButtonProps } from "@/types";
import { forwardRef } from "react";
import { cn } from "flixburst-utils";

const Button = forwardRef<HTMLButtonElement, ButtonProps>(({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return <Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />;
});

Button.displayName = "Button";

export { Button };
